/**
 * <copyright>
 * </copyright>
 *
 * $Id: AlwaysOnNodeValidator.java 12828 2009-05-15 10:13:10Z mwild $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.BindingCache;
import com.jennic.ZPSConfiguration.DiscoveryCache;
import com.jennic.ZPSConfiguration.TrustCenter;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.AlwaysOnNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AlwaysOnNodeValidator {
	boolean validate();

	boolean validateDiscoveryCache(DiscoveryCache value);
	boolean validateBindingCache(BindingCache value);
	boolean validateTrustCenter(TrustCenter value);
	boolean validatePermitJoiningTime(short value);
}
