/**
 * <copyright>
 * </copyright>
 *
 * $Id: ChannelMaskValidator.java 12828 2009-05-15 10:13:10Z mwild $
 */
package com.jennic.ZPSConfiguration.validation;


/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.ChannelMask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChannelMaskValidator {
	boolean validate();

	boolean validateChannel11(boolean value);
	boolean validateChannel12(boolean value);
	boolean validateChannel13(boolean value);
	boolean validateChannel14(boolean value);
	boolean validateChannel15(boolean value);
	boolean validateChannel16(boolean value);
	boolean validateChannel17(boolean value);
	boolean validateChannel18(boolean value);
	boolean validateChannel19(boolean value);
	boolean validateChannel20(boolean value);
	boolean validateChannel21(boolean value);
	boolean validateChannel22(boolean value);
	boolean validateChannel23(boolean value);
	boolean validateChannel24(boolean value);
	boolean validateChannel25(boolean value);
	boolean validateChannel26(boolean value);
}
