/**
 * <copyright>
 * </copyright>
 *
 * $Id: DiscoveryTableValidator.java 12828 2009-05-15 10:13:10Z mwild $
 */
package com.jennic.ZPSConfiguration.validation;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.DiscoveryTable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DiscoveryTableValidator {
	boolean validate();

	boolean validateSize(BigInteger value);
}
