/**
 * <copyright>
 * </copyright>
 *
 * $Id: EndPointValidator.java 12828 2009-05-15 10:13:10Z mwild $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.InputCluster;
import com.jennic.ZPSConfiguration.Node;
import com.jennic.ZPSConfiguration.OutputCluster;
import com.jennic.ZPSConfiguration.Profile;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.EndPoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EndPointValidator {
	boolean validate();

	boolean validateInputClusters(EList<InputCluster> value);
	boolean validateOutputClusters(EList<OutputCluster> value);
	boolean validateId(short value);
	boolean validateDiscoverable(boolean value);
	boolean validateEnabled(boolean value);
	boolean validateApplicationDeviceId(Object value);
	boolean validateApplicationDeviceVersion(byte value);
	boolean validateProfile(Profile value);
	boolean validateMessage(String value);
	boolean validateNode(Node value);
}
