/**
 * <copyright>
 * </copyright>
 *
 * $Id: NodeValidator.java 78102 2016-03-24 15:35:29Z nxp29741 $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.BindingTable;
import com.jennic.ZPSConfiguration.ChannelMask;
import com.jennic.ZPSConfiguration.ComplexDescriptor;
import com.jennic.ZPSConfiguration.DiscoveryTable;
import com.jennic.ZPSConfiguration.EndPoint;
import com.jennic.ZPSConfiguration.GroupTable;
import com.jennic.ZPSConfiguration.NodeDescriptor;
import com.jennic.ZPSConfiguration.NodePowerDescriptor;
import com.jennic.ZPSConfiguration.PDUManager;
import com.jennic.ZPSConfiguration.UserDescriptor;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateEndpoints(EList<EndPoint> value);
	boolean validateDiscoveryTable(DiscoveryTable value);
	boolean validateBindingTable(BindingTable value);
	boolean validateComplexDescriptor(ComplexDescriptor value);
	boolean validateUserDescriptor(UserDescriptor value);
	boolean validatePDUConfiguration(PDUManager value);
	boolean validateNonMemberRadius(byte value);
	boolean validateGroupTable(GroupTable value);
	boolean validateMaxNumSimultaneousApsdeAckReq(BigInteger value);
	boolean validateAPSDuplicateTableSize(BigInteger value);
	boolean validateChannelMask(ChannelMask value);
	boolean validateDiscoveryNeighbourTableSize(BigInteger value);
	boolean validateActiveNeighbourTableSize(BigInteger value);
	boolean validateRouteDiscoveryTableSize(BigInteger value);
	boolean validateRoutingTableSize(BigInteger value);
	boolean validateBroadcastTransactionTableSize(BigInteger value);
	boolean validateRouteRecordTableSize(BigInteger value);
	boolean validateAddressMapTableSize(BigInteger value);
	boolean validateSecurityMaterialSets(BigInteger value);
	boolean validateNodeDescriptor(NodeDescriptor value);
	boolean validateNodePowerDescriptor(NodePowerDescriptor value);
	boolean validateMaxNumSimultaneousApsdeReq(int value);
	boolean validateMACMutexName(String value);
	boolean validateZPSMutexName(String value);

	boolean validateFragmentationMaxNumSimulRx(int value);

	boolean validateFragmentationMaxNumSimulTx(int value);

	boolean validateFragmentationMxNumSimulTx(int value);

	boolean validateDefaultEventMessageName(String value);

	boolean validateMACDcfmIndMessage(String value);

	boolean validateMACTimeEventMessage(String value);

	boolean validateApsNonMemberRadius(int value);

	boolean validateApsNonMemberRadius(byte value);

	boolean validateApsDesignatedCoordinator(boolean value);

	boolean validateApsUseInsecureJoin(boolean value);

	boolean validateApsMaxWindowSize(int value);

	boolean validateApsInterframeDelay(int value);

	boolean validateApsSecurityTimeoutPeriod(BigInteger value);

	boolean validateAPSDuplicateTableSize(int value);
}
