/**
 * <copyright>
 * </copyright>
 *
 * $Id: NodePowerDescriptorValidator.java 12828 2009-05-15 10:13:10Z mwild $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.PowerModes;
import com.jennic.ZPSConfiguration.PowerSources;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.NodePowerDescriptor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodePowerDescriptorValidator {
	boolean validate();

	boolean validateConstantPower(boolean value);
	boolean validateRechargeableBattery(boolean value);
	boolean validateDisposableBattery(boolean value);
	boolean validateDefaultPowerSource(PowerSources value);
	boolean validateDefaultPowerMode(PowerModes value);
}
