/**
 * <copyright>
 * </copyright>
 *
 * $Id: NotImplementedValidator.java 12828 2009-05-15 10:13:10Z mwild $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.BindingCache;
import com.jennic.ZPSConfiguration.ComplexDescriptor;
import com.jennic.ZPSConfiguration.DiscoveryCache;
import com.jennic.ZPSConfiguration.DiscoveryTable;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.NotImplemented}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NotImplementedValidator {
	boolean validate();

	boolean validateComplexDescriptor(ComplexDescriptor value);
	boolean validateDiscoveryTable(DiscoveryTable value);
	boolean validateDiscoveryCache(DiscoveryCache value);
	boolean validateBindingCache(BindingCache value);
}
