/**
 * <copyright>
 * </copyright>
 *
 * $Id: OutputClusterValidator.java 12828 2009-05-15 10:13:10Z mwild $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.APDU;
import com.jennic.ZPSConfiguration.Cluster;
import com.jennic.ZPSConfiguration.EndPoint;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.OutputCluster}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OutputClusterValidator {
	boolean validate();

	boolean validateCluster(Cluster value);
	boolean validateEndPoint(EndPoint value);
	boolean validateTxAPDUs(EList<APDU> value);
}
