/**
 * <copyright>
 * </copyright>
 *
 * $Id: PDUManagerValidator.java 78102 2016-03-24 15:35:29Z nxp29741 $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.APDU;
import com.jennic.ZPSConfiguration.Node;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.PDUManager}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PDUManagerValidator {
	boolean validate();

	boolean validateAPDUs(EList<APDU> value);
	boolean validateContainerNode(Node value);
	boolean validateNumNPDUs(BigInteger value);

	boolean validatePDUMMutexName(String value);
}
