/**
 * <copyright>
 * </copyright>
 *
 * $Id: ProfileValidator.java 12828 2009-05-15 10:13:10Z mwild $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.Cluster;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.Profile}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProfileValidator {
	boolean validate();

	boolean validateId(Object value);
	boolean validateClusters(EList<Cluster> value);
}
