/**
 * <copyright>
 * </copyright>
 *
 * $Id: ZDOCommonServersValidator.java 30112 2011-03-18 18:50:09Z nxp29741 $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.ActiveEpServer;
import com.jennic.ZPSConfiguration.BindUnbindServer;
import com.jennic.ZPSConfiguration.DefaultServer;
import com.jennic.ZPSConfiguration.DeviceAnnceServer;
import com.jennic.ZPSConfiguration.ExtendedActiveEpServer;
import com.jennic.ZPSConfiguration.ExtendedSimpleDescServer;
import com.jennic.ZPSConfiguration.IeeeAddrServer;
import com.jennic.ZPSConfiguration.MatchDescServer;
import com.jennic.ZPSConfiguration.MgmtLeaveServer;
import com.jennic.ZPSConfiguration.MgmtLqiServer;
import com.jennic.ZPSConfiguration.MgmtNWKUpdateServer;
import com.jennic.ZPSConfiguration.MgmtRtgServer;
import com.jennic.ZPSConfiguration.NodeDescServer;
import com.jennic.ZPSConfiguration.NwkAddrServer;
import com.jennic.ZPSConfiguration.PermitJoiningServer;
import com.jennic.ZPSConfiguration.PowerDescServer;
import com.jennic.ZPSConfiguration.SimpleDescServer;
import com.jennic.ZPSConfiguration.SystemServerDiscoveryServer;
import com.jennic.ZPSConfiguration.ZdoClient;
import com.jennic.ZPSConfiguration.BindRequestServer;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.ZDOCommonServers}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ZDOCommonServersValidator {
	boolean validate();

	boolean validateDefaultServer(DefaultServer value);
	boolean validateZdoClient(ZdoClient value);
	boolean validateDeviceAnnceServer(DeviceAnnceServer value);
	boolean validateActiveEpServer(ActiveEpServer value);
	boolean validateNwkAddrServer(NwkAddrServer value);
	boolean validateIeeeAddrServer(IeeeAddrServer value);
	boolean validateSystemServerDiscoveryServer(SystemServerDiscoveryServer value);
	boolean validatePermitJoiningServer(PermitJoiningServer value);
	boolean validateNodeDescServer(NodeDescServer value);
	boolean validatePowerDescServer(PowerDescServer value);
	boolean validateMatchDescServer(MatchDescServer value);
	boolean validateSimpleDescServer(SimpleDescServer value);
	boolean validateMgmtLqiServer(MgmtLqiServer value);
	boolean validateMgmtRtgServer(MgmtRtgServer value);
	boolean validateMgmtLeaveServer(MgmtLeaveServer value);
	boolean validateMgmtNWKUpdateServer(MgmtNWKUpdateServer value);
	boolean validateBindUnbindServer(BindUnbindServer value);
	boolean validateExtendedActiveEpServer(ExtendedActiveEpServer value);
	boolean validateExtendedSimpleDescServer(ExtendedSimpleDescServer value);
	boolean validateBindRequestServer(BindRequestServer value);
}
