/**
 * <copyright>
 * </copyright>
 *
 * $Id: ZigbeeWirelessNetworkValidator.java 12828 2009-05-15 10:13:10Z mwild $
 */
package com.jennic.ZPSConfiguration.validation;

import com.jennic.ZPSConfiguration.ChildNodes;
import com.jennic.ZPSConfiguration.Coordinator;
import com.jennic.ZPSConfiguration.Profile;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.jennic.ZPSConfiguration.ZigbeeWirelessNetwork}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ZigbeeWirelessNetworkValidator {
	boolean validate();

	boolean validateProfiles(EList<Profile> value);
	boolean validateCoordinator(Coordinator value);
	boolean validateChildNodes(EList<ChildNodes> value);
	boolean validateExtendedPANId(Object value);
	boolean validateNonMemberRadius(byte value);
}
